### ISSUE TITLE
Confusing error output in case of mn2pdf.jar failure

### ISSUE THREAD

**Issue by maxirmx** [metanorma/mn2pdf-ruby#34]
IMHO it needs to be better formatted and/or annotated
Otherwise it is very hard to understand
![error](https://user-images.githubusercontent.com/2081498/223228968-fa6b20fb-c828-4973-ab5e-e709904afa40.jpg)

**Comment by CAMOBAP** [comment]
I think it will be more clear if we will order:
- mn2pdf stdout
- mn2pdf stderr
- ruby stack trace

@maxirmx how do you think?

**Comment by maxirmx** [comment]
Agree
If you fix it, please add some headers/annotations/separators as well.  For me the most difficult thing was to understand that this text comes from three different sources. 
Thank you

**Comment by ronaldtse** [comment]
Agree that every line should be prefixed so we know which line refers to which component. Thanks!

**Comment by CAMOBAP** [comment]
Also I have found that in there is no java in PATH it will print no error message. Just CLI and stacktrace:

```
java -Xss5m -Xmx2048m -Dapple.awt.UIElement=true -jar /Users/camobap/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/mn2pdf-1.62/lib/../bin/mn2pdf.jar --xml-file "/Users/camobap/Developers/Projects/riboseinc/metanorma/iso-19135/_site/documents/iso-19135-2021/document.presentation.xml" --xsl-file "/Users/camobap/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/bundler/gems/metanorma-iso-217ce8acb420/lib/isodoc/iso/iso.international-standard.xsl" --pdf-file "/Users/camobap/Developers/Projects/riboseinc/metanorma/iso-19135/_site/documents/iso-19135-2021/document.pdf" --param baseassetpath="/Users/camobap/Developers/Projects/riboseinc/metanorma/iso-19135/sources/iso-19135-2021" --syntax-highlight  --font-manifest "/var/folders/9_/plmb2sws0k1_8s29w7d6hqfh0000gn/T/fontist_locations20230308-8339-afp2w5.yml"
/Users/camobap/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/mn2pdf-1.62/lib/mn2pdf.rb:79:in `mn2pdf'
/Users/camobap/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/mn2pdf-1.62/lib/mn2pdf.rb:54:in `block in convert'
/Users/camobap/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/mn2pdf-1.62/lib/mn2pdf.rb:100:in `block in dump_fontist_manifest_locations'
/Users/camobap/.rbenv/versions/3.1.1/lib/ruby/3.1.0/tempfile.rb:358:in `create'
/Users/camobap/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/mn2pdf-1.62/lib/mn2pdf.rb:96:in `dump_fontist_manifest_locations'
/Users/camobap/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/mn2pdf-1.62/lib/mn2pdf.rb:52:in `convert'
/Users/camobap/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/bundler/gems/isodoc-0a6c8e212b77/lib/metanorma/output/xslfo.rb:10:in `convert'
/Users/camobap/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/bundler/gems/isodoc-0a6c8e212b77/lib/isodoc/xslfo_convert.rb:59:in `convert'
/Users/camobap/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/bundler/gems/metanorma-iso-217ce8acb420/lib/metanorma/iso/processor.rb:58:in `output'
/Users/camobap/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/metanorma-1.5.6/lib/metanorma/compile.rb:150:in `process_output_threaded'
/Users/camobap/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/metanorma-1.5.6/lib/metanorma/compile.rb:142:in `block in process_exts1'
/Users/camobap/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/metanorma-1.5.6/lib/metanorma/worker_pool.rb:11:in `block (4 levels) in initialize'
/Users/camobap/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/metanorma-1.5.6/lib/metanorma/worker_pool.rb:9:in `loop'
/Users/camobap/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/metanorma-1.5.6/lib/metanorma/worker_pool.rb:9:in `block (3 levels) in initialize'
/Users/camobap/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/metanorma-1.5.6/lib/metanorma/worker_pool.rb:8:in `catch'
/Users/camobap/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/metanorma-1.5.6/lib/metanorma/worker_pool.rb:8:in `block (2 levels) in initialize'
```

I will update PR to handle this case too

**Comment by CAMOBAP** [comment]
Done

**Comment by CAMOBAP** [comment]
1.62.1 released
