### ISSUE TITLE
Ubuntu: Access denied exception

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn2pdf-ruby#38]
Source issues: https://github.com/ituob/service-publications-docs/issues/34, https://github.com/metanorma/mn2pdf/issues/188

PR for testing: https://github.com/ituob/service-publications-docs/pull/41

From https://github.com/ituob/service-publications-docs/actions/runs/4498259502/jobs/7914666095?pr=41:
```
java -Xss5m -Xmx2048m -Djava.awt.headless=true -jar /tmp/packed-mn-20230323-2085-wsvc3d/mn2pdf.jar --xml-file "/home/runner/work/service-publications-docs/service-publications-docs/_site/documents/1117-E.212A/T-SP-E.212A-2017-A.presentation.xml" --xsl-file "/tmp/packed-mn-20230323-2085-wsvc3d/itu.service-publication.xsl" --pdf-file "/home/runner/work/service-publications-docs/service-publications-docs/_site/documents/1117-E.212A/T-SP-E.212A-2017-A.pdf" --param baseassetpath="/home/runner/work/service-publications-docs/service-publications-docs/1117-E.212A" --syntax-highlight  --font-manifest "/tmp/fontist_locations20230323-2085-qwhsu4.yml"
[mn2pdf] Fatal error!
[mn2pdf] STDOUT:
[mn2pdf] mn2pdf
[mn2pdf] STDERR:
[mn2pdf] Preparing...
[mn2pdf] Input: XML (/home/runner/work/service-publications-docs/service-publications-docs/_site/documents/1117-E.212A/T-SP-E.212A-2017-A.presentation.xml)
[mn2pdf] Input: XSL (/tmp/packed-mn-20230323-2085-wsvc3d/itu.service-publication.xsl)
[mn2pdf] Input: XSL parameters ({baseassetpath=/home/runner/work/service-publications-docs/service-publications-docs/1117-E.212A})
[mn2pdf] Output: PDF (/home/runner/work/service-publications-docs/service-publications-docs/_site/documents/1117-E.212A/T-SP-E.212A-2017-A.pdf)
[mn2pdf] 
[mn2pdf] [INFO] Generation of XSL-FO with information about the table's widths ...
[mn2pdf] [INFO] Generation of Intermediate Format with information about the table's widths ...
[mn2pdf] WARNING: Font file '/home/runner/.metanorma/fonts/trado.ttf' (font name 'Traditional Arabic', font style 'normal', font weight 'normal') doesn't exist. Replaced by '/home/runner/.metanorma/fonts/NotoSans-Regular.ttf'.
[mn2pdf] WARNING: Font file '/home/runner/.metanorma/fonts/tradbdo.ttf' (font name 'Traditional Arabic', font style 'normal', font weight 'bold') doesn't exist. Replaced by '/home/runner/.metanorma/fonts/NotoSans-Bold.ttf'.
[mn2pdf] WARNING: Font file '/home/runner/.metanorma/fonts/trado.ttf' (font name 'Traditional Arabic', font style 'italic', font weight 'normal') doesn't exist. Replaced by '/home/runner/.metanorma/fonts/NotoSans-Italic.ttf'.
[mn2pdf] WARNING: Font file '/home/runner/.metanorma/fonts/tradbdo.ttf' (font name 'Traditional Arabic', font style 'italic', font weight 'bold') doesn't exist. Replaced by '/home/runner/.metanorma/fonts/NotoSans-BoldItalic.ttf'.
[mn2pdf] 
[mn2pdf] java.nio.file.AccessDeniedException: /home/runner/.metanorma/fonts
[mn2pdf] 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
[mn2pdf] 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:[106](https://github.com/ituob/service-publications-docs/actions/runs/4498259502/jobs/7914666095?pr=41#step:7:114))
[mn2pdf] 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:[111](https://github.com/ituob/service-publications-docs/actions/runs/4498259502/jobs/7914666095?pr=41#step:7:119))

...

XSL-FO file for debugging saved into: /home/runner/work/service-publications-docs/service-publications-docs/_site/documents/1117-E.212A/T-SP-E.212A-2017-A.pdf.fo.debug.xml
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/mn2pdf-1.64/lib/mn2pdf.rb:80:in `mn2pdf'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/mn2pdf-1.64/lib/mn2pdf.rb:65:in `block in mn2pdf_hash'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/mn2pdf-1.64/lib/mn2pdf.rb:110:in `block in dump_fontist_manifest_locations'
/__tebako_memfs__/lib/ruby/2.7.0/tempfile.rb:332:in `create'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/mn2pdf-1.64/lib/mn2pdf.rb:106:in `dump_fontist_manifest_locations'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/mn2pdf-1.64/lib/mn2pdf.rb:63:in `mn2pdf_hash'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/mn2pdf-1.64/lib/mn2pdf.rb:43:in `convert'
/__tebako_memfs__/local/metanorma:119:in `convert'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-2.5.0/lib/metanorma/output/xslfo.rb:10:in `convert'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-2.5.0/lib/isodoc/xslfo_convert.rb:59:in `convert'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-itu-2.2.7/lib/metanorma/itu/processor.rb:45:in `output'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.7/lib/metanorma/compile.rb:150:in `process_output_threaded'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.7/lib/metanorma/compile.rb:142:in `block in process_exts1'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.7/lib/metanorma/worker_pool.rb:11:in `block (4 levels) in initialize'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.7/lib/metanorma/worker_pool.rb:9:in `loop'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.7/lib/metanorma/worker_pool.rb:9:in `block (3 levels) in initialize'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.7/lib/metanorma/worker_pool.rb:8:in `catch'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.7/lib/metanorma/worker_pool.rb:8:in `block (2 levels) in initialize'
```

For MacOS the process ends successfully: https://github.com/ituob/service-publications-docs/actions/runs/4498259502/jobs/7914666203?pr=41

**Comment by Intelligent2013** [comment]
No more issue: https://github.com/ituob/service-publications-docs/actions/runs/4886030615/jobs/8720849259?pr=39
